### ISSUE TITLE
Full HTTP API testing on HAPI

### ISSUE THREAD

**Issue by sdiemert** [PhysiciansDataCollaborative/knowledge-base#35]
- Need to find out how best to manage all dependencies on components like Auth and MongoDB.
- Might be best to write a test component in docker that does it all for us. 
- Need to confirm that API conforms to docs in README.md

**Comment by DerekRoberts** [comment]
We could script (bash, make) the dependency installations and checks.  Docker (stack.git) is stable enough for additions.
