### ISSUE TITLE
Osler adpater not consuming full reposne from QGateway

### ISSUE THREAD

**Issue by fieranmason** [PhysiciansDataCollaborative/knowledge-base#92]

**Comment by fieranmason** [comment]
The problem is that there are two 'ok' aka 200 reponse situations --- 1 - the record is received and imported without error 2 - the record is recieved and successfully filtered out based on the absence of the assignedAuthor id in the provider.txt file.

**Comment by DerekRoberts** [comment]
Duplicate of #91.

**Comment by fieranmason** [comment]
Not a duplicate --- different details for Oscar and Osler

**Comment by DerekRoberts** [comment]
Archived.
