### ISSUE TITLE
Shared physical resources between Nagios and server side solution components

### ISSUE THREAD

**Issue by fieranmason** [PhysiciansDataCollaborative/knowledge-base#93]

**Comment by fieranmason** [comment]
In the current deployment, Nagios and the NRPE server are both coexisting on the same physical resources (the PDC server). The NRPE server is also setup to coexist in the same container as the query composer. This sharing of resources means that Nagios and NRPE cannot be effectively used to monitor the health of the server side components.

**Comment by DerekRoberts** [comment]
Archived.
